image: alpine

stages:
  - build_and_launch
  - documentation

build_and_launch:
  stage: build_and_launch
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_03_strIU7ng/
  - make app.exe
  - ./start_app.sh
  - make test
  - ./start_all_tests.sh
  - cd
  artifacts:
    paths:
    - public

documentation:
  stage: documentation
  script:
  - apk update && apk add doxygen
  - doxygen sem_03_strIU7ng/doxygen/Doxyfile
  - mv sem_03_strIU7ng/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master