image: alpine

stages:
  - build
  - documentation

bulid:
  stage: build
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_03_strIU7ng/
  - make app.exe
  - make test
  - cd
  artifacts:
    paths:
    - public
  only:
  - master

documentation:
  stage: documentation
  script:
  - apk update && apk add doxygen
  - doxygen sem_03_strIU7ng/doxygen/Doxyfile
  - mv sem_03_strIU7ng/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master