image: alpine

stages:
  - sem_03_build
  - sem_03_documentation
  - sem_04_build
  - sem_04_documentation
  - cloc
  - cppcheck

sem_03_build:
  stage: sem_03_build
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_03_strIU7ng/
  - make app.exe
  - ./start_app.sh
  - make test
  - ./start_all_tests.sh
  - cd
  artifacts:
    paths:
    - public
  only:
  - master

sem_03_documentation:
  stage: sem_03_documentation
  script:
  - apk update && apk add doxygen
  - doxygen sem_03_strIU7ng/doxygen/Doxyfile
  - mv sem_03_strIU7ng/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  
sem_04_build:
  stage: sem_04_build
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_04_liu7st
  - make
  - ./app.exe
  - make test.exe
  - ./start_testing.sh
  - cd
  artifacts:
    paths:
    - public
  only:
  - master

sem_04_documentation:
  stage: sem_04_documentation
  script:
  - apk update && apk add doxygen
  - doxygen sem_04_liu7st/doxygen/Doxyfile
  - mv sem_04_liu7st/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

cloc:
  stage: cloc
  script:
  - apk add --update cloc
  - cloc --report-file=report.txt *
  - cat report.txt
  only:
  - master

cppcheck:
  stage: cppcheck
  script:
  - apk add --update cppcheck
  - cppcheck --language=c --enable=warning,missingInclude,style --std=c99 --inconclusive --error-exitcode=1 */*.c
  