image: alpine

stages:
  - sem_03_striu7ng
  - sem_04_liu7st

sem_03:
  stage: sem_03_striu7ng
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_03_strIU7ng/
  - make app.exe
  - ./start_app.sh
  - make test
  - ./start_all_tests.sh
  - cd
  - apk update && apk add doxygen
  - doxygen sem_03_strIU7ng/doxygen/Doxyfile
  - mv sem_03_strIU7ng/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

sem_04:
  stage: sem_04_liu7st
  script:
  - apk add --update make
  - apk add --no-cache gcc musl-dev
  - cd sem_04_liu7st
  - make test.exe
  - cd
  artifacts:
    paths:
    - public

